name: Terraform status check actions

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform initialization
        run: terrafrom init
      - name: Vailidate terraform
        run: terraform validate
